version: 2

project_name: gh-app-check

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: gh-app-check
    main: .
    binary: gh-app-check
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

changelog:
  use: github

release:
  github:
    owner: wakeward
    name: gh-app-check
  prerelease: auto
